project:
  type: website

website:
  title: "Hello!"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Project 1.qmd

format:
  html:
    theme: quartz
    css: styles.css
    toc: true

editor: visual

